"""Enable cascade delete for tokens

Revision ID: 036693eb5a67
Revises: db55b2e03d00
Create Date: 2025-12-07 18:53:51.760619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036693eb5a67'
down_revision = 'db55b2e03d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tokens_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tokens_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
