"""empty message

Revision ID: 24b4e64630c2
Revises: c8e609365550
Create Date: 2025-12-16 06:25:45.636450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '24b4e64630c2'
down_revision = 'c8e609365550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cache', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
