"""Insurance and reservation tables

Revision ID: 3b4948bcb93b
Revises: 
Create Date: 2025-12-01 11:11:33.327150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4948bcb93b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('car_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED', 'COMPLETED', name='reservationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('insurance_policie',
    sa.Column('insurance_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.PrimaryKeyConstraint('insurance_id'),
    sa.UniqueConstraint('policy_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_policie')
    op.drop_table('reservations')
    # ### end Alembic commands ###
