"""autodelete_insurnacepolicies

Revision ID: c55b9d3a36e1
Revises: a6ca74e8eadb
Create Date: 2025-12-14 02:07:23.979167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55b9d3a36e1'
down_revision = 'a6ca74e8eadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('insurance_policies_reservation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reservations', ['reservation_id'], ['reservation_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('insurance_policies_reservation_id_fkey'), 'reservations', ['reservation_id'], ['reservation_id'])

    # ### end Alembic commands ###
