"""added usr table

Revision ID: d3c2188e0e37
Revises: 
Create Date: 2025-12-02 18:03:52.243909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c2188e0e37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('car_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED', 'COMPLETED', name='reservationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('driver_license', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('insurance_policies',
    sa.Column('insurance_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.PrimaryKeyConstraint('insurance_id'),
    sa.UniqueConstraint('policy_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_policies')
    op.drop_table('users')
    op.drop_table('reservations')
    # ### end Alembic commands ###
