"""enable cascade delete on access_logs

Revision ID: db55b2e03d00
Revises: 77e312828a46
Create Date: 2025-12-07 18:46:56.287835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db55b2e03d00'
down_revision = '77e312828a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('access_logs_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('access_logs_employee_id_fkey'), 'users', ['employee_id'], ['id'])
        batch_op.alter_column('action',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
